//: @nochecks for testing @nometrics for testing
unit Test.Search.Functions;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, Windows, SysUtils, Classes, Graphics, 
  Search.Types;

type
  TDGHTestCase = Class(TTestCase)
  Public
    Procedure CheckTolerance(dblExpected, dblActual, dblTolerance : Double; strMsg : String = '');
  End;

  TTestSearchFunctions = Class(TDGHTestCase)
  Strict Private
    FParams    : TStringList;
    FSwitch    : Integer;
    FIndex     : Integer;
    FFileAttrs : TSearchFileAttrs;
    FLDate     : TDateTime;
    FUDate     : TDateTime;
  Strict Protected
    Procedure GetAttributesException;
    Procedure GetDateRangeException;
  Public
  Published
    procedure TestIncrementSwitchPosition;
    Procedure TestGetRangeString;
    Procedure TestGetDateRange;
    Procedure TestGetSummaryLevel;
    Procedure TestGetSizeRange;
    Procedure TestGetAttributes;
    Procedure TestGetOrderBy;
    Procedure TestGetSearchInInfo;
    Procedure TestGetDateType;
    Procedure TestGetExclusions;
    Procedure TestGetOwnerSwitch;
    Procedure TestOutputAttributes;
    procedure TestCheckSizeRange;
    procedure TestCheckFileAttributes;
    Procedure TestCheckExclusions;
    Procedure TestCheckOwner;
    Procedure TestGetColourSwitch;
    Procedure TestCheckDateRange;
    Procedure TestGetSizeFormat;
    Procedure TestCheckConsoleMode;
    Procedure TestGetConsoleTitle;
    Procedure TestFileAttrsToAttrsSet;
  End;

implementation

Uses
  Search.Functions,
  Search.FilesCls;

procedure TDGHTestCase.CheckTolerance(dblExpected, dblActual, dblTolerance: Double; strMsg: String = '');
begin
  Check(Abs(dblExpected - dblActual) < dblTolerance,
    Format('%s : Expected %1.4f, Actual %1.4f (Delta %1.4f)',
    [strMsg, dblExpected, dblActual, Abs(dblExpected - dblActual)]));
end;

{ TestApplicationFunctions }

Procedure TTestSearchFunctions.GetAttributesException;

Begin
  GetAttributes(FParams, FSwitch, FIndex, FFileAttrs);
End;

Procedure TTestSearchFunctions.GetDateRangeException;

Begin
  GetDateRange(FParams, FSwitch, FIndex, FLDate, FUdate);
End;

procedure TTestSearchFunctions.TestCheckConsoleMode;
begin

end;

procedure TTestSearchFunctions.TestCheckDateRange;
begin

end;

procedure TTestSearchFunctions.TestCheckExclusions;

Var
  slExclusions : TstringList;
  strPath : String;
  recSearch : TSearchRec;
  boolFound : Boolean;

begin
  slExclusions := TStringList.Create;
  Try
    slExclusions.Add('\borland\');
    slExclusions.Add('myfile.pas');
    strPath := 'C:\Program Files\Boland\BDS\4.0\Source\';
    recSearch.Name := 'MyFile.dfm';
    boolFound := True;
    CheckExclusions(strPath, recSearch.Name, boolFound, slExclusions);
    CheckEquals(True, boolFound, 'Test 1');
    strPath := 'C:\Program Files\Borland\BDS\4.0\Source\';
    boolFound := True;
    CheckExclusions(strPath, recSearch.Name, boolFound, slExclusions);
    CheckEquals(False, boolFound, 'Test 2');
    strPath := 'C:\Program Files\Boland\BDS\4.0\Source\';
    recSearch.Name := 'MyFile.pas';
    boolFound := True;
    CheckExclusions(strPath, recSearch.Name, boolFound, slExclusions);
    CheckEquals(False, boolFound, 'Test 3');
    strPath := 'C:\Program Files\Borland\BDS\4.0\Source\';
    recSearch.Name := 'MyFile.pas';
    boolFound := True;
    CheckExclusions(strPath, recSearch.Name, boolFound, slExclusions);
    CheckEquals(False, boolFound, 'Test 4');
  Finally
    slExclusions.Free;
  End;
end;

procedure TTestSearchFunctions.TestCheckFileAttributes;

Var
  recSearch : TSearchRec;
  setSearchAttrs : TSearchFileAttrs;
  boolFound : Boolean;

begin
  CommandLineSwitches := [clsAttrRange];
  recSearch.Attr := 0;
  setSearchAttrs := [sfaReadOnly];
  boolFound := True;
  CheckFileAttributes(setSearchAttrs, FileAttrsToAttrsSet(recSearch.Attr), boolFound);
  CheckEquals(False, boolFound, 'Test 1');
  recSearch.Attr := faReadOnly Or faArchive Or faSysFile Or faHidden;
  setSearchAttrs := [sfaFile];
  boolFound := True;
  CheckFileAttributes(setSearchAttrs, FileAttrsToAttrsSet(recSearch.Attr), boolFound);
  CheckEquals(True, boolFound, 'Test 2');
  setSearchAttrs := [sfaReadOnly];
  boolFound := True;
  CheckFileAttributes(setSearchAttrs, FileAttrsToAttrsSet(recSearch.Attr), boolFound);
  CheckEquals(True, boolFound, 'Test 3');
  setSearchAttrs := [sfaArchive];
  boolFound := True;
  CheckFileAttributes(setSearchAttrs, FileAttrsToAttrsSet(recSearch.Attr), boolFound);
  CheckEquals(True, boolFound, 'Test 4');
  setSearchAttrs := [];
  boolFound := True;
  CheckFileAttributes(setSearchAttrs, FileAttrsToAttrsSet(recSearch.Attr), boolFound);
  CheckEquals(True, boolFound, 'Test 5');
  setSearchAttrs := [sfaSystem];
  boolFound := True;
  CheckFileAttributes(setSearchAttrs, FileAttrsToAttrsSet(recSearch.Attr), boolFound);
  CheckEquals(True, boolFound, 'Test 6');
  setSearchAttrs := [sfaHidden];
  boolFound := True;
  CheckFileAttributes(setSearchAttrs, FileAttrsToAttrsSet(recSearch.Attr), boolFound);
  CheckEquals(True, boolFound, 'Test 7');
  setSearchAttrs := [sfaReadOnly, sfaArchive];
  boolFound := True;
  CheckFileAttributes(setSearchAttrs, FileAttrsToAttrsSet(recSearch.Attr), boolFound);
  CheckEquals(True, boolFound, 'Test 8');
  setSearchAttrs := [];
  boolFound := True;
  CheckFileAttributes(setSearchAttrs, FileAttrsToAttrsSet(recSearch.Attr), boolFound);
  CheckEquals(True, boolFound, 'Test 9');
end;

procedure TTestSearchFunctions.TestCheckOwner;

Var
  bool : Boolean;

begin
  bool := True;
  CheckOwner('Rail\HoylD', 'Rail\HoylD', ospExact, osEquals, bool);
  Check(bool, 'Test 1');
  bool := True;
  CheckOwner('Rail\HoylD', 'Rail\Hoyle', ospExact, osNotEquals, bool);
  Check(bool, 'Test 2');
  bool := True;
  CheckOwner('Rail\HoylD', 'HoylD', ospEnd, osEquals, bool);
  Check(bool, 'Test 3');
  bool := True;
  CheckOwner('Rail\HoylD', 'Rail\Hoyl', ospStart, osEquals, bool);
  Check(bool, 'Test 4');
  bool := True;
  CheckOwner('Rail\HoylD', 'Hoyl', ospMiddle, osEquals, bool);
  Check(bool, 'Test 5');
end;

procedure TTestSearchFunctions.TestCheckSizeRange;

Var
  iSize, iLSize, iUSize : Int64;
  bool : Boolean;

begin
  CommandLineSwitches := [clsSizeRange];
  iLSize := 1000;
  iUSize := 2000;
  iSize := 1500;
  bool := True;
  CheckSizeRange(iSize, iLSize, iUSize, bool);
  Check(bool, 'Test 1');
  iSize := 500;
  bool := True;
  CheckSizeRange(iSize, iLSize, iUSize, bool);
  Check(Not bool, 'Test 2');
  iSize := 2500;
  bool := True;
  CheckSizeRange(iSize, iLSize, iUSize, bool);
  Check(Not bool, 'Test 3');
end;

Procedure TTestSearchFunctions.TestFileAttrsToAttrsSet;

Begin
End;

procedure TTestSearchFunctions.TestGetAttributes;

Begin
  FParams := TstringList.Create;
  Try
    FParams.Text := 'My.exe'#13#10'*.pas';
    FSwitch := 1;
    FIndex := 2;
    CheckException(GetAttributesException, ESearchException);
    FParams.Text := 'my.exe'#13#10'/t[F]';
    FSwitch := 1;
    FIndex := 2;
    GetAttributes(FParams, FSwitch, FIndex, FFileAttrs);
    Check(FFileAttrs = [sfaFile]);
    FParams.Text := 'my.exe'#13#10'/t[D]';
    FSwitch := 1;
    FIndex := 2;
    GetAttributes(FParams, FSwitch, FIndex, FFileAttrs);
    Check(FFileAttrs = [sfaDirectory]);
    FParams.Text := 'my.exe'#13#10'/t[V]';
    FSwitch := 1;
    FIndex := 2;
    GetAttributes(FParams, FSwitch, FIndex, FFileAttrs);
    Check(FFileAttrs = [sfaVolume]);
    FParams.Text := 'my.exe'#13#10'/t[R]';
    FSwitch := 1;
    FIndex := 2;
    GetAttributes(FParams, FSwitch, FIndex, FFileAttrs);
    Check(FFileAttrs = [sfaReadOnly]);
    FParams.Text := 'my.exe'#13#10'/t[A]';
    FSwitch := 1;
    FIndex := 2;
    GetAttributes(FParams, FSwitch, FIndex, FFileAttrs);
    Check(FFileAttrs = [sfaArchive]);
    FParams.Text := 'my.exe'#13#10'/t[S]';
    FSwitch := 1;
    FIndex := 2;
    GetAttributes(FParams, FSwitch, FIndex, FFileAttrs);
    Check(FFileAttrs = [sfaSystem]);
    FParams.Text := 'my.exe'#13#10'/t[H]';
    FSwitch := 1;
    FIndex := 2;
    GetAttributes(FParams, FSwitch, FIndex, FFileAttrs);
    Check(FFileAttrs = [sfaHidden]);
    FParams.Text := 'my.exe'#13#10'/t[FRASH]';
    FSwitch := 1;
    FIndex := 2;
    GetAttributes(FParams, FSwitch, FIndex, FFileAttrs);
    Check(FFileAttrs = [sfaReadOnly, sfaArchive, sfaSystem, sfaHidden, sfaFile]);
  Finally
    FParams.Free;
  End;
end;

Procedure TTestSearchFunctions.TestGetColourSwitch;

Var
  sl: TStringList;
  slColour : TStringList;

Begin
  sl := TStringList.Create;
  Try
    slColour := TStringList.Create;
    Try
      sl.Text := 'my.exe'#13#10'/l';
      FSwitch := 1;
      FIndex := 2;
      GetColoursSwitch(sl, FSwitch, FIndex, slColour);
      CheckEquals(2, FIndex);
      CheckEquals(0, slColour.Count);
      sl.Text := 'my.exe'#13#10'/l[MyColour=clRed]';
      FSwitch := 1;
      FIndex := 2;
      GetColoursSwitch(sl, FSwitch, FIndex, slColour);
      CheckEquals(18, FIndex);
      CheckEquals(1, slColour.Count);
      CheckEquals('MyColour=clRed', slColour[0]);
    Finally
      slColour.Free;
    End;
  Finally
    sl.Free;
  End;
End;

procedure TTestSearchFunctions.TestGetConsoleTitle;
begin

end;

procedure TTestSearchFunctions.TestGetDateRange;

Const
  dblTolerance = 1 / (24 * 60 * 60 * 999);

begin
  FParams := TStringList.Create;
  Try
    FParams.Text := 'My.exe'#13#10'/d';
    FSwitch := 1;
    FIndex := 2;
    CheckException(GetDateRangeException, ESearchException);
    FParams.Text := 'My.exe'#13#10'/d[';
    FSwitch := 1;
    FIndex := 2;
    CheckException(GetDateRangeException, ESearchException);
    FParams.Text := 'My.exe'#13#10'/d[-';
    FSwitch := 1;
    FIndex := 2;
    CheckException(GetDateRangeException, ESearchException);
    FParams.Text := 'My.exe'#13#10'/d[-]';
    FSwitch := 1;
    FIndex := 2;
    GetDateRange(FParams, FSwitch, FIndex, FLDate, FUdate);
    CheckTolerance(FLDate, EncodeDate(1900, 1, 1) + EncodeTime(0, 0, 0, 0), dblTolerance, 'Test 1.1');
    CheckTolerance(FUdate, EncodeDate(2099, 12, 31) + EncodeTime(23, 59, 59, 999), dblTolerance, 'Test 1.2');
    FParams.Text := 'My.exe'#13#10'/d[12/Jan/2007-]';
    FSwitch := 1;
    FIndex := 2;
    GetDateRange(FParams, FSwitch, FIndex, FLDate, FUdate);
    CheckTolerance(FLDate, EncodeDate(2007, 1, 12) + EncodeTime(0, 0, 0, 0), dblTolerance, 'Test 2.1');
    CheckTolerance(FUdate, EncodeDate(2099, 12, 31) + EncodeTime(23, 59, 59, 999), dblTolerance, 'Test 2.2');
    FParams.Text := 'My.exe'#13#10'/d[12/Jan/2007-31/Jan/2007]';
    FSwitch := 1;
    FIndex := 2;
    GetDateRange(FParams, FSwitch, FIndex, FLDate, FUdate);
    CheckTolerance(FLDate, EncodeDate(2007, 1, 12) + EncodeTime(0, 0, 0, 0), dblTolerance, 'Test 3.1');
    CheckTolerance(FUdate, EncodeDate(2007, 1, 31) + EncodeTime(23, 59, 59, 999), dblTolerance, 'Test 3.2');
    FParams.Text := 'My.exe'#13#10'/d[12/Jan/2007 12:34-31/Jan/2007 23:50]';
    FSwitch := 1;
    FIndex := 2;
    GetDateRange(FParams, FSwitch, FIndex, FLDate, FUdate);
    CheckTolerance(FLDate, EncodeDate(2007, 1, 12) + EncodeTime(12, 34, 0, 0), dblTolerance, 'Test 4.1');
    CheckTolerance(FUdate, EncodeDate(2007, 1, 31) + EncodeTime(23, 50, 0, 0), dblTolerance, 'Test 4.2');
  Finally
    FParams.Free;
  End;
end;

procedure TTestSearchFunctions.TestGetDateType;

Var
  slParams : TStringList;
  iSwitch, iIndex : Integer;
  DateType : TDateType;

begin
  slParams := TStringList.Create;
  Try
    slParams.Text := 'my.exe'#13#10'/e';
    iSwitch := 1;
    iIndex := 2;
    Try
      GetDateType(slParams, iSwitch, iIndex, DateType);
    Except
      On E : ESearchException Do
        Check(True);
      Else
        Check(False);
    End;
    slParams.Text := 'my.exe'#13#10'/e:';
    iSwitch := 1;
    iIndex := 2;
    Try
      GetDateType(slParams, iSwitch, iIndex, DateType);
    Except
      On E : ESearchException Do
        Check(True);
      Else
        Check(False);
    End;
    slParams.Text := 'my.exe'#13#10'/e:z';
    iSwitch := 1;
    iIndex := 2;
    Try
      GetDateType(slParams, iSwitch, iIndex, DateType);
    Except
      On E : ESearchException Do
        Check(True);
      Else
        Check(False);
    End;
    slParams.Text := 'my.exe'#13#10'/e:c';
    iSwitch := 1;
    iIndex := 2;
    GetDateType(slParams, iSwitch, iIndex, DateType);
    Check(dtCreation = DateType, 'Test 1');
    slParams.Text := 'my.exe'#13#10'/e:a';
    iSwitch := 1;
    iIndex := 2;
    GetDateType(slParams, iSwitch, iIndex, DateType);
    Check(dtLastAccess = DateType, 'Test 2');
    slParams.Text := 'my.exe'#13#10'/e:w';
    iSwitch := 1;
    iIndex := 2;
    GetDateType(slParams, iSwitch, iIndex, DateType);
    Check(dtLastWrite = DateType, 'Test 3');
  Finally
    slParams.Free;
  End;
end;

procedure TTestSearchFunctions.TestGetExclusions;

Var
  slParams : TStringList;
  iSwitch, iIndex : Integer;
  strExlFileName : String;

begin
  slParams := TStringList.Create;
  Try
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/x';
    Try
      GetExclusions(slParams, iSwitch, iIndex, strExlFileName);
    Except
      On E : ESearchException Do
        Check(True);
      Else
        Check(False);
    End;
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/x[';
    Try
      GetExclusions(slParams, iSwitch, iIndex, strExlFileName);
    Except
      On E : ESearchException Do
        Check(True);
      Else
        Check(False);
    End;
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/x[filename';
    Try
      GetExclusions(slParams, iSwitch, iIndex, strExlFileName);
    Except
      On E : ESearchException Do
        Check(True);
      Else
        Check(False);
    End;
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/x[filename]';
    GetExclusions(slParams, iSwitch, iIndex, strExlFileName);
    CheckEquals('filename', strExlFileName, 'Test 1');
  Finally
    slParams.Free;
  End;
end;

procedure TTestSearchFunctions.TestGetOrderBy;

Var
  slParams : TStringList;
  iSwitch, iIndex : Integer;
  OrderFilesDirection : TOrderDirection;
  OrderFilesBy : TOrderBy;


begin
  slParams := TStringList.Create;
  Try
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/o';
    Try
      GetOrderBy(slParams, iSwitch, iIndex, OrderFilesDirection, OrderFilesBy);
    Except
      On E: Exception Do
        Check(True);
      Else
        Check(False);
    End;
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/o:';
    Try
      GetOrderBy(slParams, iSwitch, iIndex, OrderFilesDirection, OrderFilesBy);
    Except
      On E: Exception Do
        Check(True);
      Else
        Check(False);
    End;
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/o:z';
    Try
      GetOrderBy(slParams, iSwitch, iIndex, OrderFilesDirection, OrderFilesBy);
    Except
      On E: Exception Do
        Check(True);
      Else
        Check(False);
    End;
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/o:n';
    GetOrderBy(slParams, iSwitch, iIndex, OrderFilesDirection, OrderFilesBy);
    Check(OrderFilesDirection = odAscending, 'Test 1.1');
    Check(OrderFilesBy = obName, 'Test 1.2');
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/o:+n';
    GetOrderBy(slParams, iSwitch, iIndex, OrderFilesDirection, OrderFilesBy);
    Check(OrderFilesDirection = odAscending, 'Test 1.3');
    Check(OrderFilesBy = obName, 'Test 1.4');
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/o:-n';
    GetOrderBy(slParams, iSwitch, iIndex, OrderFilesDirection, OrderFilesBy);
    Check(OrderFilesDirection = odDescending, 'Test 1.5');
    Check(OrderFilesBy = obName, 'Test 1.6');
    iSwitch := 1;
    iIndex := 2;
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/o:d';
    GetOrderBy(slParams, iSwitch, iIndex, OrderFilesDirection, OrderFilesBy);
    Check(OrderFilesDirection = odAscending, 'Test 3.1');
    Check(OrderFilesBy = obDate, 'Test 3.2');
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/o:+d';
    GetOrderBy(slParams, iSwitch, iIndex, OrderFilesDirection, OrderFilesBy);
    Check(OrderFilesDirection = odAscending, 'Test 3.3');
    Check(OrderFilesBy = obDate, 'Test 3.4');
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/o:-d';
    GetOrderBy(slParams, iSwitch, iIndex, OrderFilesDirection, OrderFilesBy);
    Check(OrderFilesDirection = odDescending, 'Test 3.5');
    Check(OrderFilesBy = obDate, 'Test 3.6');
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/o:o';
    GetOrderBy(slParams, iSwitch, iIndex, OrderFilesDirection, OrderFilesBy);
    Check(OrderFilesDirection = odAscending, 'Test 4.1');
    Check(OrderFilesBy = obOwner, 'Test 4.2');
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/o:+o';
    GetOrderBy(slParams, iSwitch, iIndex, OrderFilesDirection, OrderFilesBy);
    Check(OrderFilesDirection = odAscending, 'Test 4.3');
    Check(OrderFilesBy = obOwner, 'Test 4.4');
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/o:-o';
    GetOrderBy(slParams, iSwitch, iIndex, OrderFilesDirection, OrderFilesBy);
    Check(OrderFilesDirection = odDescending, 'Test 4.5');
    Check(OrderFilesBy = obOwner, 'Test 4.6');
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/o:s';
    GetOrderBy(slParams, iSwitch, iIndex, OrderFilesDirection, OrderFilesBy);
    Check(OrderFilesDirection = odAscending, 'Test 5.1');
    Check(OrderFilesBy = obSize, 'Test 5.2');
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/o:+s';
    GetOrderBy(slParams, iSwitch, iIndex, OrderFilesDirection, OrderFilesBy);
    Check(OrderFilesDirection = odAscending, 'Test 5.3');
    Check(OrderFilesBy = obSize, 'Test 5.4');
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/o:-s';
    GetOrderBy(slParams, iSwitch, iIndex, OrderFilesDirection, OrderFilesBy);
    Check(OrderFilesDirection = odDescending, 'Test 5.5');
    Check(OrderFilesBy = obSize, 'Test 5.6');
  Finally
    slParams.Free;
  End;
end;

procedure TTestSearchFunctions.TestGetOwnerSwitch;

Var
  slParams : TStringList;
  iSwitch, iIndex : Integer;
  OwnerSearch : TOwnerSearch;
  OwnerSearchPos : TOwnerSearchPos;
  strOwnerSearch : String;

begin
  slParams := TStringList.Create;
  Try
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/w';
    GetOwnerSwitch(slParams, iSwitch, iIndex, OwnerSearch, OwnerSearchPos, strOwnerSearch);
    Check(OwnerSearch = osEquals, 'Test 1.1');
    Check(OwnerSearchPos = ospNone, 'Test 1.2');
    CheckEquals('', strOwnerSearch, 'Test 1.3');
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/w[';
    Try
      GetOwnerSwitch(slParams, iSwitch, iIndex, OwnerSearch, OwnerSearchPos, strOwnerSearch);
    Except
      On E: Exception Do
        Check(True);
      Else
        Check(False);
    End;
    slParams.Text := 'my.exe'#13#10'/w[HoylD';
    Try
      GetOwnerSwitch(slParams, iSwitch, iIndex, OwnerSearch, OwnerSearchPos, strOwnerSearch);
    Except
      On E: Exception Do
        Check(True);
      Else
        Check(False);
    End;
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/w[hoyld]';
    GetOwnerSwitch(slParams, iSwitch, iIndex, OwnerSearch, OwnerSearchPos, strOwnerSearch);
    Check(OwnerSearch = osEquals, 'Test 2.1');
    Check(OwnerSearchPos = ospExact, 'Test 2.2');
    CheckEquals('hoyld', strOwnerSearch, 'Test 2.3');
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/w[!hoyld]';
    GetOwnerSwitch(slParams, iSwitch, iIndex, OwnerSearch, OwnerSearchPos, strOwnerSearch);
    Check(OwnerSearch = osNotEquals, 'Test 3.1');
    Check(OwnerSearchPos = ospExact, 'Test 3.2');
    CheckEquals('hoyld', strOwnerSearch, 'Test 3.3');
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/w[*hoyld]';
    GetOwnerSwitch(slParams, iSwitch, iIndex, OwnerSearch, OwnerSearchPos, strOwnerSearch);
    Check(OwnerSearch = osEquals, 'Test 4.1');
    Check(OwnerSearchPos = ospEnd, 'Test 4.2');
    CheckEquals('hoyld', strOwnerSearch, 'Test 4.3');
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/w[!*hoyld]';
    GetOwnerSwitch(slParams, iSwitch, iIndex, OwnerSearch, OwnerSearchPos, strOwnerSearch);
    Check(OwnerSearch = osNotEquals, 'Test 5.1');
    Check(OwnerSearchPos = ospEnd, 'Test 5.2');
    CheckEquals('hoyld', strOwnerSearch, 'Test 5.3');
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/w[hoyld*]';
    GetOwnerSwitch(slParams, iSwitch, iIndex, OwnerSearch, OwnerSearchPos, strOwnerSearch);
    Check(OwnerSearch = osEquals, 'Test 6.1');
    Check(OwnerSearchPos = ospStart, 'Test 6.2');
    CheckEquals('hoyld', strOwnerSearch, 'Test 6.3');
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/w[!hoyld*]';
    GetOwnerSwitch(slParams, iSwitch, iIndex, OwnerSearch, OwnerSearchPos, strOwnerSearch);
    Check(OwnerSearch = osNotEquals, 'Test 7.1');
    Check(OwnerSearchPos = ospStart, 'Test 7.2');
    CheckEquals('hoyld', strOwnerSearch, 'Test 7.3');
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/w[*hoyld*]';
    GetOwnerSwitch(slParams, iSwitch, iIndex, OwnerSearch, OwnerSearchPos, strOwnerSearch);
    Check(OwnerSearch = osEquals, 'Test 8.1');
    Check(OwnerSearchPos = ospMiddle, 'Test 8.2');
    CheckEquals('hoyld', strOwnerSearch, 'Test 8.3');
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/w[!*hoyld*]';
    GetOwnerSwitch(slParams, iSwitch, iIndex, OwnerSearch, OwnerSearchPos, strOwnerSearch);
    Check(OwnerSearch = osNotEquals, 'Test 9.1');
    Check(OwnerSearchPos = ospMiddle, 'Test 9.2');
    CheckEquals('hoyld', strOwnerSearch, 'Test 9.3');
  Finally
    slParams.Free;
  End;
end;

procedure TTestSearchFunctions.TestGetRangeString;

Var
  slParams : TStringList;
  iSwitch, iIndex : Integer;
  chEndToken : TSearchCharSet;
  strExceptionMsg : String;
  strValue : String;

begin
  slParams := TStringList.Create;
  Try
    iSwitch := 1;
    iIndex := 3;
    chEndToken := ['-'];
    slParams.Text := 'my.exe'#13#10'/s[1000-2000]';
    GetRangeString(slParams, chEndToken, strExceptionMsg, iIndex, iSwitch, strValue);
    CheckEquals('1000', strValue, 'Test 1');
    iSwitch := 1;
    iIndex := 8;
    chEndToken := [']'];
    slParams.Text := 'my.exe'#13#10'/s[1000-2000]';
    GetRangeString(slParams, chEndToken, strExceptionMsg, iIndex, iSwitch, strValue);
    CheckEquals('2000', strValue, 'Test 2');
    iSwitch := 1;
    iIndex := 8;
    chEndToken := ['z'];
    slParams.Text := 'my.exe'#13#10'/s[1000-2000]';
    Try
      GetRangeString(slParams, chEndToken, strExceptionMsg, iIndex, iSwitch, strValue);
    Except
      On E : ESearchException Do
        Check(True);
      Else
        Check(False);
    End;
  Finally
    slParams.Free;
  End;
end;

procedure TTestSearchFunctions.TestGetSearchInInfo;

Var
  slParams : TStringList;
  iSwitch, iIndex : Integer;
  strSearchInText : String;
  iLines: Integer;

begin
  slParams := TStringList.Create;
  Try
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/i';
    Try
      GetSearchInInfo(slParams, iSwitch, iIndex, strSearchInText, iLines);
      Check(False, 'First Exception');
    Except
      On E: ESearchException Do
        Check(True);
      Else
        Check(False, 'First Exception');
    End;
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/i[';
    Try
      GetSearchInInfo(slParams, iSwitch, iIndex, strSearchInText, iLines);
      Check(False, 'Second Exception');
    Except
      On E: ESearchException Do
        Check(True);
      Else
        Check(False, 'Second Exception');
    End;
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/i[hello';
    Try
      GetSearchInInfo(slParams, iSwitch, iIndex, strSearchInText, iLines);
      Check(False, 'Third Exception');
    Except
      On E: ESearchException Do
        Check(True);
      Else
        Check(False, 'Third Exception');
    End;
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/i[hello]';
    GetSearchInInfo(slParams, iSwitch, iIndex, strSearchInText, iLines);
    CheckEquals('hello', strSearchInText, 'Test 1');
  Finally
    slParams.Free;
  End;
end;

procedure TTestSearchFunctions.TestGetSizeFormat;
begin

end;

procedure TTestSearchFunctions.TestGetSizeRange;

Var
  slParams : TStringList;
  iSwitch, iIndex : Integer;
  iLSize, iUSize : Int64;

begin
  slParams := TStringList.Create;
  Try
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/z';
    Try
      GetSizeRange(slParams, iSwitch, iIndex, iLSize, iUSize);
    Except
      On E : ESearchException Do
        Check(True);
      Else
        Check(False);
    End;
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/z[';
    Try
      GetSizeRange(slParams, iSwitch, iIndex, iLSize, iUSize);
    Except
      On E : ESearchException Do
        Check(True);
      Else
        Check(False);
    End;
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/z[-';
    Try
      GetSizeRange(slParams, iSwitch, iIndex, iLSize, iUSize);
    Except
      On E : ESearchException Do
        Check(True);
      Else
        Check(False);
    End;
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/z[-]';
    GetSizeRange(slParams, iSwitch, iIndex, iLSize, iUSize);
    CheckEquals(0, iLSize, 'Test 1.1');
    CheckEquals($F00000000000000, iUSize, 'Test 1.2');
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/z[1000-]';
    GetSizeRange(slParams, iSwitch, iIndex, iLSize, iUSize);
    CheckEquals(1000, iLSize, 'Test 2.1');
    CheckEquals($F00000000000000, iUSize, 'Test 2.2');
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/z[-2000]';
    GetSizeRange(slParams, iSwitch, iIndex, iLSize, iUSize);
    CheckEquals(0, iLSize, 'Test 3.1');
    CheckEquals(2000, iUSize, 'Test 3.2');
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/z[1000-2000]';
    GetSizeRange(slParams, iSwitch, iIndex, iLSize, iUSize);
    CheckEquals(1000, iLSize, 'Test 4.1');
    CheckEquals(2000, iUSize, 'Test 4.2');
  Finally
    slParams.Free;
  End;
end;

procedure TTestSearchFunctions.TestGetSummaryLevel;

Var
  slParams : TStringList;
  iSwitch, iIndex, iSummaryLevel : Integer;

begin
  slParams := TStringList.Create;
  Try
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/1';
    iSummaryLevel := 1;
    Try
      GetSummaryLevel(slParams, iSwitch, iIndex, iSummaryLevel);
    Except
      On E : ESearchException Do
        Check(True);
      Else
        Check(False);
    End;
    iSwitch := 1;
    iIndex := 2;
    slParams.Text := 'my.exe'#13#10'/1';
    iSummaryLevel := 0;
    GetSummaryLevel(slParams, iSwitch, iIndex, iSummaryLevel);
    CheckEquals(1, iSummaryLevel, 'Test 1.1');
  Finally
    slParams.Free;
  End;
end;

procedure TTestSearchFunctions.TestIncrementSwitchPosition;

Var
  sl : TStringList;
  iIndex, iSwitch : Integer;

begin
  sl := TstringList.Create;
  Try
    sl.Add('EXE');
    sl.Add('Item1');
    sl.Add('Item2');
    iIndex := 1;
    iSwitch := 1;
    IncrementSwitchPosition(sl, iIndex, iSwitch, 'Test Failure.');
    CheckEquals(2, iIndex);
    iIndex := 5;
    iSwitch := 1;
    Try
      IncrementSwitchPosition(sl, iIndex, iSwitch, 'Test Failure.');
    Except
      On E : ESearchException Do
        Check(True);
      Else
        Check(False);
    End;
  Finally
    sl.Free;
  End;
end;

procedure TTestSearchFunctions.TestOutputAttributes;

Var
  S : String;

begin
  S := OutputAttributes([]);
  CheckEquals('....F..........', S, 'Empty');
  S := OutputAttributes([sfaArchive]);
  CheckEquals('.A..F..........', S, 'Archive');
  S := OutputAttributes([sfaReadOnly]);
  CheckEquals('R...F..........', S, 'ReadOnly');
  S := OutputAttributes([sfaSystem]);
  CheckEquals('..S.F..........', S, 'System');
  S := OutputAttributes([sfaHidden]);
  CheckEquals('...HF..........', S, 'Hidden');
  S := OutputAttributes([sfaReadOnly, sfaArchive, sfaSystem, sfaHidden]);
  CheckEquals('RASHF..........', S, 'Readony, Archive, System, Hidden and File');
  S := OutputAttributes([sfaReadOnly, sfaArchive, sfaSystem, sfaHidden, sfaDirectory]);
  CheckEquals('RASHD..........', S, 'RASHD');
  S := OutputAttributes([sfaReadOnly, sfaArchive, sfaSystem, sfaHidden, sfaVolume]);
  CheckEquals('RASHV..........', S, 'RASHV');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest('Search Functions', TTestSearchFunctions.Suite);
end.
